#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 大学生志愿者管理系统1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VOLUNTEER")]
	public partial class queue1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertACTapply_T(ACTapply_T instance);
    partial void UpdateACTapply_T(ACTapply_T instance);
    partial void DeleteACTapply_T(ACTapply_T instance);
    partial void InsertActivityT(ActivityT instance);
    partial void UpdateActivityT(ActivityT instance);
    partial void DeleteActivityT(ActivityT instance);
    #endregion
		
		public queue1DataContext() : 
				base(global::大学生志愿者管理系统1.Properties.Settings.Default.VOLUNTEERConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public queue1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public queue1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public queue1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public queue1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACTapply_T> ACTapply_T
		{
			get
			{
				return this.GetTable<ACTapply_T>();
			}
		}
		
		public System.Data.Linq.Table<ActivityT> ActivityT
		{
			get
			{
				return this.GetTable<ActivityT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACTapply_T")]
	public partial class ACTapply_T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Aqueue_ID;
		
		private System.Nullable<int> _Vol_ID;
		
		private System.Nullable<int> _Act_ID;
		
		private string _Act_Name;
		
		private string _Act_place;
		
		private System.Nullable<int> _Need;
		
		private System.Nullable<int> _Qty;
		
		private string _Holder;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAqueue_IDChanging(int value);
    partial void OnAqueue_IDChanged();
    partial void OnVol_IDChanging(System.Nullable<int> value);
    partial void OnVol_IDChanged();
    partial void OnAct_IDChanging(System.Nullable<int> value);
    partial void OnAct_IDChanged();
    partial void OnAct_NameChanging(string value);
    partial void OnAct_NameChanged();
    partial void OnAct_placeChanging(string value);
    partial void OnAct_placeChanged();
    partial void OnNeedChanging(System.Nullable<int> value);
    partial void OnNeedChanged();
    partial void OnQtyChanging(System.Nullable<int> value);
    partial void OnQtyChanged();
    partial void OnHolderChanging(string value);
    partial void OnHolderChanged();
    #endregion
		
		public ACTapply_T()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aqueue_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Aqueue_ID
		{
			get
			{
				return this._Aqueue_ID;
			}
			set
			{
				if ((this._Aqueue_ID != value))
				{
					this.OnAqueue_IDChanging(value);
					this.SendPropertyChanging();
					this._Aqueue_ID = value;
					this.SendPropertyChanged("Aqueue_ID");
					this.OnAqueue_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vol_ID", DbType="Int")]
		public System.Nullable<int> Vol_ID
		{
			get
			{
				return this._Vol_ID;
			}
			set
			{
				if ((this._Vol_ID != value))
				{
					this.OnVol_IDChanging(value);
					this.SendPropertyChanging();
					this._Vol_ID = value;
					this.SendPropertyChanged("Vol_ID");
					this.OnVol_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_ID", DbType="Int")]
		public System.Nullable<int> Act_ID
		{
			get
			{
				return this._Act_ID;
			}
			set
			{
				if ((this._Act_ID != value))
				{
					this.OnAct_IDChanging(value);
					this.SendPropertyChanging();
					this._Act_ID = value;
					this.SendPropertyChanged("Act_ID");
					this.OnAct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_Name", DbType="NVarChar(50)")]
		public string Act_Name
		{
			get
			{
				return this._Act_Name;
			}
			set
			{
				if ((this._Act_Name != value))
				{
					this.OnAct_NameChanging(value);
					this.SendPropertyChanging();
					this._Act_Name = value;
					this.SendPropertyChanged("Act_Name");
					this.OnAct_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Act_place", DbType="NVarChar(50)")]
		public string Act_place
		{
			get
			{
				return this._Act_place;
			}
			set
			{
				if ((this._Act_place != value))
				{
					this.OnAct_placeChanging(value);
					this.SendPropertyChanging();
					this._Act_place = value;
					this.SendPropertyChanged("Act_place");
					this.OnAct_placeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Need", DbType="Int")]
		public System.Nullable<int> Need
		{
			get
			{
				return this._Need;
			}
			set
			{
				if ((this._Need != value))
				{
					this.OnNeedChanging(value);
					this.SendPropertyChanging();
					this._Need = value;
					this.SendPropertyChanged("Need");
					this.OnNeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int")]
		public System.Nullable<int> Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Holder", DbType="NVarChar(50)")]
		public string Holder
		{
			get
			{
				return this._Holder;
			}
			set
			{
				if ((this._Holder != value))
				{
					this.OnHolderChanging(value);
					this.SendPropertyChanging();
					this._Holder = value;
					this.SendPropertyChanged("Holder");
					this.OnHolderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActivityT")]
	public partial class ActivityT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _activity_ID;
		
		private string _activity_Name;
		
		private string _activity_type;
		
		private System.DateTime _addtime;
		
		private System.DateTime _stoptime;
		
		private string _place;
		
		private System.Nullable<int> _renshu;
		
		private string _Image;
		
		private string _descn;
		
		private System.Nullable<int> _ShengyuNum;
		
		private string _Holder;
		
		private string _status;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onactivity_IDChanging(int value);
    partial void Onactivity_IDChanged();
    partial void Onactivity_NameChanging(string value);
    partial void Onactivity_NameChanged();
    partial void Onactivity_typeChanging(string value);
    partial void Onactivity_typeChanged();
    partial void OnaddtimeChanging(System.DateTime value);
    partial void OnaddtimeChanged();
    partial void OnstoptimeChanging(System.DateTime value);
    partial void OnstoptimeChanged();
    partial void OnplaceChanging(string value);
    partial void OnplaceChanged();
    partial void OnrenshuChanging(System.Nullable<int> value);
    partial void OnrenshuChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    partial void OndescnChanging(string value);
    partial void OndescnChanged();
    partial void OnShengyuNumChanging(System.Nullable<int> value);
    partial void OnShengyuNumChanged();
    partial void OnHolderChanging(string value);
    partial void OnHolderChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public ActivityT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int activity_ID
		{
			get
			{
				return this._activity_ID;
			}
			set
			{
				if ((this._activity_ID != value))
				{
					this.Onactivity_IDChanging(value);
					this.SendPropertyChanging();
					this._activity_ID = value;
					this.SendPropertyChanged("activity_ID");
					this.Onactivity_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string activity_Name
		{
			get
			{
				return this._activity_Name;
			}
			set
			{
				if ((this._activity_Name != value))
				{
					this.Onactivity_NameChanging(value);
					this.SendPropertyChanging();
					this._activity_Name = value;
					this.SendPropertyChanged("activity_Name");
					this.Onactivity_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity_type", DbType="NVarChar(50)")]
		public string activity_type
		{
			get
			{
				return this._activity_type;
			}
			set
			{
				if ((this._activity_type != value))
				{
					this.Onactivity_typeChanging(value);
					this.SendPropertyChanging();
					this._activity_type = value;
					this.SendPropertyChanged("activity_type");
					this.Onactivity_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addtime", DbType="DateTime NOT NULL")]
		public System.DateTime addtime
		{
			get
			{
				return this._addtime;
			}
			set
			{
				if ((this._addtime != value))
				{
					this.OnaddtimeChanging(value);
					this.SendPropertyChanging();
					this._addtime = value;
					this.SendPropertyChanged("addtime");
					this.OnaddtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stoptime", DbType="DateTime NOT NULL")]
		public System.DateTime stoptime
		{
			get
			{
				return this._stoptime;
			}
			set
			{
				if ((this._stoptime != value))
				{
					this.OnstoptimeChanging(value);
					this.SendPropertyChanging();
					this._stoptime = value;
					this.SendPropertyChanged("stoptime");
					this.OnstoptimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place", DbType="NVarChar(50)")]
		public string place
		{
			get
			{
				return this._place;
			}
			set
			{
				if ((this._place != value))
				{
					this.OnplaceChanging(value);
					this.SendPropertyChanging();
					this._place = value;
					this.SendPropertyChanged("place");
					this.OnplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_renshu", DbType="Int")]
		public System.Nullable<int> renshu
		{
			get
			{
				return this._renshu;
			}
			set
			{
				if ((this._renshu != value))
				{
					this.OnrenshuChanging(value);
					this.SendPropertyChanging();
					this._renshu = value;
					this.SendPropertyChanged("renshu");
					this.OnrenshuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(200)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descn", DbType="NVarChar(255)")]
		public string descn
		{
			get
			{
				return this._descn;
			}
			set
			{
				if ((this._descn != value))
				{
					this.OndescnChanging(value);
					this.SendPropertyChanging();
					this._descn = value;
					this.SendPropertyChanged("descn");
					this.OndescnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShengyuNum", DbType="Int")]
		public System.Nullable<int> ShengyuNum
		{
			get
			{
				return this._ShengyuNum;
			}
			set
			{
				if ((this._ShengyuNum != value))
				{
					this.OnShengyuNumChanging(value);
					this.SendPropertyChanging();
					this._ShengyuNum = value;
					this.SendPropertyChanged("ShengyuNum");
					this.OnShengyuNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Holder", DbType="NVarChar(50)")]
		public string Holder
		{
			get
			{
				return this._Holder;
			}
			set
			{
				if ((this._Holder != value))
				{
					this.OnHolderChanging(value);
					this.SendPropertyChanging();
					this._Holder = value;
					this.SendPropertyChanged("Holder");
					this.OnHolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
